# EPIZAP
Ferramenta computacional para predição de epítopos a partir de dados de Phage Display

## Requirements

### NEXTFLOW

This application was developed and tested on NEXTFLOW version 24.10.4;

-> Nextflow can be used on any POSIX-compatible system (Linux, macOS, etc), and on Windows through WSL. It requires Bash 3.2 (or later) and Java 17 (or later, up to 23). You can see which version you have using the following command:
java -version

More details on: https://www.nextflow.io/docs/latest/install.html

### DOCKER

https://docs.docker.com/get-started/

### Image from docker Hub

https://hub.docker.com/r/gianlucamajor/epizap

### Current version

docker pull gianlucamajor/epizap:v0.3.0-alpha

## Quick start

### Clone the repository

```
git clone https://github.com/gianlucamajor/epizap.git
cd epizap
```

### EPIZAP Smoke Test

The smoke test is a quick preliminary check that verifies whether the system's critical features are working.

For the smoke test we use a small set of DNA inserts that map to the kinetoplast DNA (kDNA) minicircles of T. cruzi.


So just run:

```
nextflow epizap.nf
```

These files are already included in the project and set as default parameters.

```
--reads dataSet/kDNA_gPhage/DNA_inserts_kDNA.fastq
--peptides dataSet/kDNA_gPhage/peptides_encoded_by_kDNA_inserts.fasta
--ref dataSet/kDNA_gPhage/y_strain_minicircles.fasta
--annotation dataSet/kDNA_gPhage/annotation_genomic_dummy.gff
--outdir results
```


Expected result:

Note: this is illustrative, not the exact output. The run id (e.g. `furious_engelbart`), revision hash, and per-task ids (e.g. `[f3/78af91]`) are randomly generated by Nextflow and will differ on every machine and every run.

```
N E X T F L O W  ~  version 24.10.4

Launching `epizap.nf` [<run-name>] DSL2 - revision: <revision-hash>

===================================
Reads: dataSet/kDNA_gPhage/DNA_inserts_kDNA.fastq
Peptides: dataSet/kDNA_gPhage/peptides_encoded_by_kDNA_inserts.fasta
Reference: dataSet/kDNA_gPhage/y_strain_minicircles.fasta
Annotation: dataSet/kDNA_gPhage/annotation_genomic_dummy.gff
Graph Segment threshold: 1.00
Outdir: results
Peptiede Segment: results/peptides-segment/*.fasta
Mapper file:

===================================

executor >  local (45)
[xx/xxxxxx] mapper:IDX_BUILDER (y_strain_minicircles)                                                  [100%] 1 of 1 ✔
[xx/xxxxxx] mapper:MAPPER (DNA_inserts_kDNA)                                                            [100%] 1 of 1 ✔
[xx/xxxxxx] mapper:MAX_SCORE_MAPPING_EXTRACTOR (DNA_inserts_kDNA)                                       [100%] 1 of 1 ✔
[xx/xxxxxx] segmentRetriever:SEGMENT_EXTRACTOR (DNA_inserts_kDNA)                                       [100%] 1 of 1 ✔
[xx/xxxxxx] segmentGraphComputer:SEGMENT_GRAPH_COMPUTER (DNA_inserts_kDNA - threshold 1.00)             [100%] 1 of 1 ✔
[xx/xxxxxx] segmentRetriever:SEQUENCE_EXTRACTOR (DNA_inserts_kDNA)                                      [100%] 1 of 1 ✔
[xx/xxxxxx] segmentRetriever:SEGMENT_NOTE_TAKER (DNA_inserts_kDNA)                                      [100%] 1 of 1 ✔
[xx/xxxxxx] peptideClusteringByCC:PEPTIDE_CLUSTERING_CC (DNA_inserts_kDNA_mapped-segment-graph)         [100%] 1 of 1 ✔
[xx/xxxxxx] msa:MSA (cc-45.fasta; align)                                                                [100%] 17 of 17 ✔
[xx/xxxxxx] mview:MVIEW (cc-45)                                                                         [100%] 17 of 17 ✔
[xx/xxxxxx] predicator:PREDICATOR                                                                       [100%] 1 of 1 ✔
[xx/xxxxxx] graphUpdater:GRAPH_UPDATER (DNA_inserts_kDNA_mapped-segment-graph-graph-cc-id)               [100%] 1 of 1 ✔
[xx/xxxxxx] epitopeReporter:EPITOPE_REPORTER (DNA_inserts_kDNA_mapped-segment-graph-graph-cc-id-msa-epitopes) [100%] 1 of 1 ✔
```

The output files should be in the `results` directory ( `--outdir results`), with one subdirectory per step:

```
results/
├── y_strain_minicircles-idx/
├── mapping/
├── max-score-mapping/
├── segments/
├── segments-annotated/
├── peptides-segment/
├── peptides-clustering-cc/
├── msa/
├── mview/
├── epitopes-by-msa-core/
├── graph/
├── graph-updated/
└── epitopes_report/
```

### EPIZAP output files

The `epitopes_report/` directory holds the final output of the pipeline:

- `*.fasta` — one record per predicted epitope (consensus sequence taken from the MSA of each connected component / GAGRS).
- `*.json` — one entry per predicted epitope, with: `ID`, `Epitope` (sequence), `Number of AGRs`, `Number of Peptides`, `Number of Inserts` (and the breakdown by group when `--inserts_group` is used), `MSA` (alignment page name), `Genomic Region Locus`, and `Features` (best proteome hit, genomic region annotation, and IEDB T. cruzi / human epitope hits, when those inputs are provided).
- `*.pickle` — the updated graph (Python pickle of the networkx graph object) used to generate the FASTA/JSON reports; can be reloaded for further analysis or to re-run `epitope_reporter.py` with different options (e.g. `--inserts-group`, `--iedb`).

## EPIZAP with pre-processed gPhage data (T. cruzi)

This example uses the pre-processed gPhage dataset (DNA inserts and encoded peptides from all patient groups, merged) mapped against the *T. cruzi* Brazil Clone A4 reference genome.

### gPhage data (download required)

The gPhage input files (`DNA_inserts_all_patients_groups.fastq`, `DNA_insert_IDs_by_group.tsv`, `peptides_encoded_by_DNA_inserts.fasta`/`.tsv`) are too large to ship in this repository. They are published on Zenodo (DOI [10.5281/zenodo.20854186](https://doi.org/10.5281/zenodo.20854186)) and described in detail in [dataSet/gPhage_data/README](dataSet/gPhage_data/README).

Download them, place the `.zip` files in `dataSet/gPhage_data/`, and unzip them there before running EPIZAP. You can do this manually or with the helper script:

```
bin/download_gphage_data.sh
```

It downloads each file from Zenodo into `dataSet/gPhage_data/`, verifies its MD5 checksum and unzips it.

### Reference genome (Br-A4, already in the repo)

The *T. cruzi* Brazil Clone A4 reference genome and annotation are already included in this repository as compressed files in `dataSet/genome_ref_Br_A4/` (see [dataSet/genome_ref_Br_A4/README](dataSet/genome_ref_Br_A4/README)). They also **need to be unzipped** before use:

```
unzip dataSet/genome_ref_Br_A4/t_cruzi_br_a4.fna.zip -d dataSet/genome_ref_Br_A4/
unzip dataSet/genome_ref_Br_A4/genomic.gff.zip -d dataSet/genome_ref_Br_A4/
```

### Run

```
nextflow epizap.nf \
  --reads dataSet/gPhage_data/DNA_inserts_all_patients_groups.fastq \
  --peptides dataSet/gPhage_data/peptides_encoded_by_DNA_inserts.fasta \
  --ref dataSet/genome_ref_Br_A4/t_cruzi_br_a4.fna \
  --annotation dataSet/genome_ref_Br_A4/genomic.gff \
  --inserts_group dataSet/gPhage_data/DNA_insert_IDs_by_group.tsv \
  --outdir results_gPhage_BrA4
```
